### ISSUE TITLE
Milestone 3 Feedback

### ISSUE THREAD

**Issue by GiuseppeTT** [DSCI-310/DSCI-310-Group-4#85]
*Congratulations on finishing milestone 3! We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.*

### Analysis code is abstracted to four (or more) scripts which take command line arguments and save analysis artifacts (e.g., figures and data for tables).

- [ ] Code in one or more scripts is not of high quality, or does not adhere to the adopted code styles for the course ~~**- 3**~~ **Regraded: -2**

Commented out code, stange block of empty lines, `TODO` comments, strange comments like `# 39` in all scripts ~~but `scripts/read_data_from_url.py`~~ **Regraded: (...) but `scripts/read_data_from_url.py` and `scripts/preprocessing_data.py`**

- [ ] **(I did not take off points for this)** Consider using f-strngs instead of concatenating strings.

### Report is written in a literate code document, and the code in the literate code document primarily functions to source analysis artifacts and format the document.

- [ ] The literate code document (R Markdown or Jupyter notebook) does not use markup language syntax to reference tables and figures so that the correct table and figure numbers are automatically used **- 4**

You have captions for tables and figures but don't cross-reference them.

- [ ] The literate code document (R Markdown or Jupyter notebook) does not use code to automatically update inline values generated from the analysis that are presented in the narrated text of the document **- 4**

There are hard coded values such as "The average age of all clients is 35.419625"

- [ ] The literate code document (R Markdown or Jupyter notebook) uses markup language syntax to automatically format citations and generate a bibliography but it does not work correctly. **- 2**

There are problems with the path to references.bib

### A data analysis pipeline written in GNU Make exists, and works to run the analysis from beginning to end, as well as to clean up the analysis

- [ ] The `Makefile` does not track all target dependencies, and so some intermediate data files, or analysis artifacts may miss being generated in some cases **- 5**

Missing report rendering in the makefile `all` target. Moreover the `reports/final_report.html` and `reports/final_report.pdf` targets do not work.

- [ ] Target `all` could be simplified by writing something like `all: <report_target>`. **- 2**

### Dependencies have been updated (so it include the test libraries)

- [ ] There are missing dependencies. **- 2**

For instance, it is missing `tidyverse` and it system dependencies such as `libcurl4-openssl-dev`.

### Project file and directory structure organization

- [ ] There are folder/files that should not be committed. **- 1**

The legacy analysis file `data_analysis.ipynb` is still in the `reports/` folder.

### GitHub release

- [ ] Please provide the link to the release as `https://github.com/DSCI-310/REPOSITORY/tree/VERSION` (replacing `REPOSITORY` and `VERSION` with the correct ones for your project version for each milestone). This makes is a lot easier for someone to just visit the repository as it was at that point in the project's history. **-1**

###  Analysis can be run reproducibly using documentation provided in the README

- [ ] There are mentions of jupyter notebook file in the README, which at this points is a legacy file (.i.e. a file that is no longer used). **- 2**

- [ ] Could not reproducibly run the analysis because a package was missing from the provided computational environment. **-5**

Missing `tidyverse` and others

(base) jovyan@ea6045e5db59:~/DSCI-310-Group-4$ make reports/final_report.html
Rscript -e "rmarkdown::render('reports/final_report.Rmd')"

processing file: final_report.Rmd
  |..                                                                    |   3%
  ordinary text without R code

  |....                                                                  |   6%
label: setup (with options)
List of 1
 $ include: logi FALSE

Quitting from lines 43-46 (final_report.Rmd)
Error in library(tidyverse) : there is no package called 'tidyverse'
Calls: <Anonymous> ... withVisible -> eval_with_user_handlers -> eval -> eval -> library

Execution halted
make: *** [Makefile:27: reports/final_report.html] Error 1

If I try to install tidyverse, I got missing dependencies such as `libcurl4-openssl-dev` which I cannot install because I do not know the password for `jovyan`.

(base) jovyan@ea6045e5db59:~/DSCI-310-Group-4$ sudo apt-get install libcurl4-openssl-dev
[sudo] password for jovyan:
Sorry, try again.

Consider installing `{tidyverse}` or, even better, base your dockefile on the `rocker/tidyverse` image.
