### ISSUE TITLE
Milestone 4 feedback

### ISSUE THREAD

**Issue by GiuseppeTT** [DSCI-310/DSCI-310-Group-4#86]
*Congratulations on finishing your final project!!! This is a great accomplishment and you should be proud!
Below we list some specific feedback you can use to improve your project if you so desire,
but most importantly to learn.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.*

### Addressed feedback given by the teaching team from milestone 1

- [ ] 40% of the feedback given by the teaching team from milestone 1 was not addressed **-10**

### Addressed feedback given by the teaching team from milestone 2

- [ ] 40% of the feedback given by the teaching team from milestone 1 was not addressed **-10**

### Project file and directory structure organization

- [ ] There are folder/files that should not be committed. **- 0.5**

`src/__pycache__/`
